ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/rear_als/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp

obj-y	:=  rear_alshub.o
