# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019 MediaTek Inc.
#

obj-$(CONFIG_RT4831A_I2C)		+= rt4831a_drv.o
obj-$(CONFIG_OCP2130_I2C)		+= ocp2130_drv.o
ccflags-$(CONFIG_RT4831A_I2C) += -I$(srctree)/drivers/misc/mediatek/leds/